### ISSUE TITLE
Feedback week 1 

### ISSUE THREAD

**Issue by charder001** [thijsbordewijk/web-app-from-scratch-1920#1]
- Update your repo, missing title, description, api
- insertAdjacentHTML isn't a very secure option, look into createElement or createTextNode
- Consider error handling for your fetch
- Good naming conventions!

**Comment by Razpudding** [comment]
It's nicer if you divide your feedback into separate issues. Then, Thijs can fix and close them one by one.

**Comment by thijsbordewijk** [comment]
1. Upodated repo is on the way!
2. i will look into templating in the following days
3. error handling will also be done later on
4. :)
