### ISSUE TITLE
for loops

### ISSUE THREAD

**Issue by mordock** [thijsbordewijk/web-app-from-scratch-1920#15]
var i;
for(i=0; i < hourlyArray.length; i++) {
  totalHourlytemp += hourlyArray[i].temperature;
}
You can combine this to:
for(var i=0; i < hourlyArray.length; i++) {
  totalHourlytemp += hourlyArray[i].temperature;
}
This makes it more readable, same with the other for loops

**Comment by thijsbordewijk** [comment]
fixed!
